backend:
  name: github
  repo: biginfra/biginfra.github.io
  branch: main

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "pages"
    label: "Pages"
    files:

      - file: "index.md"
        label: "Home"
        name: "home"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Body, name: body, widget: markdown}

      - file: "about.md"
        label: "About"
        name: "about"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Body, name: body, widget: markdown}

      - file: "services.md"
        label: "Services"
        name: "services"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Body, name: body, widget: markdown}

      - file: "contact.md"
        label: "Contact"
        name: "contact"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Body, name: body, widget: markdown}
