backend:
  name: git-gateway
  branch: main

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "pages"
    label: "Pages"
    files:

      - label: Home
        name: home
        file: index.md
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Body, name: body, widget: markdown}

      - label: Declarations
        name: declarations
        file: declarations.md
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Body, name: body, widget: markdown}

      - label: Services
        name: services
        file: services.md
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Body, name: body, widget: markdown}

      - label: Payments
        name: payments
        file: payments.md
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Body, name: body, widget: markdown}
