backend:
  name: test-repo

collections:
  - name: "test"
    label: "Test"
    files:
      - file: "index.md"
        label: "Home"
        name: "home"
        fields:
          - { label: "Body", name: "body", widget: "markdown" }
